[package]
name = "cargo-asm"
version = "0.1.0"
authors = ["Adolph C. <adolphc@outlook.com>"]
edition = "2018"

[dependencies]
capstone = { path = "../capstone-rs/capstone-rs" }
gimli = "0.20"
clap = "2.33"
anyhow = "1.0"
goblin = "0.2"
rustc-demangle = "0.1"
byteorder = "1.3"
